
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANY_TEXT CIRCUMFLEX CLS COMMA DEBUG DIVIDE EQUALS ERASE EXIT FLOAT GT HELP INT LINE LIST LOAD LPAREN LT MINUS PLUS RPAREN RUN SEMI_COLON STRING_LITERAL TIMES WORD\n\tline : command\n\t\n\tcommand : list\n\t\t\t\t| exit\n\t\t\t\t| run\n\t\t\t\t| cls\n\t\t\t\t| erase\n\t\t\t\t| help\n\t\t\t\t| debug\n\t\t\t\t| load\n\t\t\t\t| program_line\n\t\t\t\t| empty\n\t\n\tlist : LIST\n\t\n\tprogram_line : INT ANY_TEXT\n\t\t\t\t\t| INT\n\t\n\thelp : HELP \n\thelp : HELP ANY_TEXT\n\t\n\terase : ERASE\n\t\n\tcls : CLS\n\t\n\trun : RUN\n\t\n\texit : EXIT\n\t\n\tdebug : DEBUG\n\t\n\tload : LOAD ANY_TEXT\n\t\n\tempty :\n\t'
    
_lr_action_items = {'LIST':([0,],[13,]),'EXIT':([0,],[14,]),'RUN':([0,],[15,]),'CLS':([0,],[16,]),'ERASE':([0,],[17,]),'HELP':([0,],[18,]),'DEBUG':([0,],[19,]),'LOAD':([0,],[20,]),'INT':([0,],[21,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,],[-23,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-20,-19,-18,-17,-15,-21,-14,-16,-22,-13,]),'ANY_TEXT':([18,20,21,],[22,23,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'command':([0,],[2,]),'list':([0,],[3,]),'exit':([0,],[4,]),'run':([0,],[5,]),'cls':([0,],[6,]),'erase':([0,],[7,]),'help':([0,],[8,]),'debug':([0,],[9,]),'load':([0,],[10,]),'program_line':([0,],[11,]),'empty':([0,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> command','line',1,'p_line','cmd_parse.py',49),
  ('command -> list','command',1,'p_command','cmd_parse.py',54),
  ('command -> exit','command',1,'p_command','cmd_parse.py',55),
  ('command -> run','command',1,'p_command','cmd_parse.py',56),
  ('command -> cls','command',1,'p_command','cmd_parse.py',57),
  ('command -> erase','command',1,'p_command','cmd_parse.py',58),
  ('command -> help','command',1,'p_command','cmd_parse.py',59),
  ('command -> debug','command',1,'p_command','cmd_parse.py',60),
  ('command -> load','command',1,'p_command','cmd_parse.py',61),
  ('command -> program_line','command',1,'p_command','cmd_parse.py',62),
  ('command -> empty','command',1,'p_command','cmd_parse.py',63),
  ('list -> LIST','list',1,'p_list','cmd_parse.py',68),
  ('program_line -> INT ANY_TEXT','program_line',2,'p_program_line','cmd_parse.py',75),
  ('program_line -> INT','program_line',1,'p_program_line','cmd_parse.py',76),
  ('help -> HELP','help',1,'p_help','cmd_parse.py',83),
  ('help -> HELP ANY_TEXT','help',2,'p_help','cmd_parse.py',84),
  ('erase -> ERASE','erase',1,'p_erase','cmd_parse.py',97),
  ('cls -> CLS','cls',1,'p_cls','cmd_parse.py',102),
  ('run -> RUN','run',1,'p_run','cmd_parse.py',108),
  ('exit -> EXIT','exit',1,'p_exit','cmd_parse.py',113),
  ('debug -> DEBUG','debug',1,'p_debug','cmd_parse.py',119),
  ('load -> LOAD ANY_TEXT','load',2,'p_load','cmd_parse.py',125),
  ('empty -> <empty>','empty',0,'p_empty','cmd_parse.py',131),
]
